version: "3.1"
volumes:
    python:
services:
    db:
        image: postgres:10-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=restaurantdb
            - POSTGRES_USER=devadmin
            - POSTGRES_PASSWORD=Ninja6708
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: sh -c "sleep 1 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
            - 3001:3001
        environment:
            - DB_HOST=localhost
            - DB_NAME=restaurantdb
            - DB_USER=devadmin
            - DB_PASS=Ninja6708
        depends_on:
            - db